import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import NameTag from "../components/NameTag";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DevloperPortfol.io - Publish your Developer Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col lg:h-screen`}>
        <div className="text-sm text-white bg-violet-500 text-center p-1 font-medium">This project is a Work in progress</div>
        <NavBar></NavBar>
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
